### ISSUE TITLE
Disabled In-Line Titles Prevent Titles from Appearing in Gallery View

### ISSUE THREAD

**Issue by trevware** [pashashocky/obsidian-note-gallery#11]
#10 I'm not a collaborator, so re-opening here. I left a comment: 

Looks like this is still not functioning as intended. Using the following code block:

```
~~~~note-gallery
showTitle: true
query: 'tag:#snippet' 
debugQuery: false
recursive: true
limit: 10
sort: desc
sortBy: mtime
fontSize: 12pt
~~~~
```

I tried repositioning the arguments, reinstalling via BRAT, but the issue persists. If I toggle show inline title on again, the titles will appear with no issue. I don't think there's anything else impacting the plugin. It's not a theme issue either, I've tested it with Default. Maybe I'm missing something?

**Comment by trevware** [comment]
Disregard. I had to quit and re-launch Obsidian.

**Comment by pashashocky** [comment]
Glad it works :) For future `Reload app without saving` command should do it too!
