### ISSUE TITLE
exclude sub-folder(s) of path

### ISSUE THREAD

**Issue by pcause** [pashashocky/obsidian-note-gallery#12]
I want to use path and go 2 levels down, but want to skip the "_attachments" and another directory I use.  Not clear how to do this.  Maybe add an "pathexclude" to allow that.

**Comment by pashashocky** [comment]
@pcause you should be able to use native obsidian search to do this. `-path: exclude/path`

https://help.obsidian.md/Plugins/Search

**Comment by pashashocky** [comment]
Closing for now - please re-open if you have issues.
