### ISSUE TITLE
Feature request: allow specifying breakpoints and columns map

### ISSUE THREAD

**Issue by HananoshikaYomaru** [pashashocky/obsidian-note-gallery#13]
I want the setting to expose this option to allow user to specify the breakpoints and corresponding columns they want

**Comment by pashashocky** [comment]
Hey @HananoshikaYomaru - back from holidays! I'll get this in!

**Comment by pashashocky** [comment]
This is now available in `0.0.57` :) Have fun, re-open if you have any issues, usage in the README.md :)
