### ISSUE TITLE
Note not showing if image is note on the vault

### ISSUE THREAD

**Issue by Chykg0** [pashashocky/obsidian-note-gallery#14]
Hello,

Thank you for your plugin, i love the idea !

I tried it, but it seems there is a little issue.

When the note contains text and local image with preview, it works very well.
But when the image in the note is on a website (and note inside the vault), the note gallery don't show that note.

I show you this in the following gif.
![Issue note gallery](https://github.com/pashashocky/obsidian-note-gallery/assets/96997587/d4896da2-074b-4ad8-83a4-dd528bfe5fc0)

I tried it on the sandbox vault and in my own local vault and that's the same.

Thank you for your plugin and your help.

**Comment by pashashocky** [comment]
Back from holiday - thank you for the report, will investigate!

**Comment by pashashocky** [comment]
haha - this turned out to be a very specific issue to the image that you used :) 
it should now be fixed in `0.0.57` - please re-open if you still have any issues!
