### ISSUE TITLE
Some minor style improvements

### ISSUE THREAD

**Issue by Azona77** [pashashocky/obsidian-note-gallery#18]
Images with specified size (like this ![[logo.png|300]]) follow the large size in the note page. 
This css snippet will make it follow the gallery width:
It should be better if this option can be set as default.

```
.card-content img{
  max-width:100%;
}
```
![image](https://github.com/pashashocky/obsidian-note-gallery/assets/76045875/e38cb82f-be82-4a47-ab81-571be8ef1623)

---

btw, the margin between title and content is too large in my minimal theme. I made some minor changes with the following css snippet:
```
.card-content p{
  margin-top: 0;
}
.note-card hr{
  display: none;
} 
.search-empty-state{
  display: none;
}
```

**Comment by pashashocky** [comment]
@Azona77 thank you for the recommendations! I'm back from holiday will get this in!

**Comment by pashashocky** [comment]
The recommended css change for img's is now in `0.0.57`, thank you for reporting!
