### ISSUE TITLE
[BUG] Note cards are slightly resized on hover

### ISSUE THREAD

**Issue by UnikZ** [pashashocky/obsidian-note-gallery#21]
I noticed that an undefined `--interactive-accent-tint` CSS variable is used for coloring note card borders on hover.
That makes the interpreter to reset border width to zero and cards become wider by 2px. In some cases card text takes less lines on hover.

According to the [documentation for developers](https://docs.obsidian.md/Reference/CSS+variables/Foundations/Colors#Interactive+colors), the `--interactive-accent` variable should be used instead of aforementioned above one.

Before:
![ezgif-1-643a7e89fa](https://github.com/pashashocky/obsidian-note-gallery/assets/575850/b71d1459-a76e-418b-9787-0993b191e639)

After:
![ezgif-1-7b43605bd8](https://github.com/pashashocky/obsidian-note-gallery/assets/575850/4d1088f9-54b5-4d28-bf78-9b90ef3f4627)

**Comment by pashashocky** [comment]
Solid find, fixed in `0.0.58`, thank you for reporting and testing!
