### ISSUE TITLE
Path appears to be ignored

### ISSUE THREAD

**Issue by macbikegeek** [pashashocky/obsidian-note-gallery#22]
Obsidian search string of 

> path: "📺 TV Shows" tag: #to-watch

returns one note which is in the 📺 TV Shows folder and has the #to-watch tag. There is another file in the folder without the tag which is not displayed.

\`\`\`note-gallery
query: 'path: "📺 TV Shows"'
query: tag:#to-watch
sort: asc
debugQuery: true
limit: 15
\`\`\`

returns all notes in my vault with the tag #to-watch, including the correct one in 📺 TV Shows.

I've tried multiple permutations with and without the single and/or double quotes and space after path:. Most return the same result set while a couple return an error.

**Comment by pashashocky** [comment]
@macbikegeek it's a little difficult to help you debug your issue as I don't see what question is being asked. Based on reading your issue, I feel that everything you mention is operating correctly. 

In your first search string you are asking for `path: TV Shows` **AND** `tag: #to-watch`. Obsidian will only return the note matching both of those filters. 

In the code-block you provided as an example, you have `query` defined twice, so the second one is taking precedence... 

You should try to build your query with the obsidian search menu or use `debugQuery: true`. Please, let me know if you figure it out or what you want exactly...

The correct syntax is `query: 'search string'`, for example:

```
~~~~note-gallery
query: 'path: Atlas tag: #test'
debugQuery: true
~~~~
```
<img width="1047" alt="SCR-20240205-ujgi" src="https://github.com/pashashocky/obsidian-note-gallery/assets/673857/a3476f16-1d75-4cf0-8e4e-7b750e696b55">

**Comment by macbikegeek** [comment]
Thanks, I mistook the examples that show multiple query lines as meaning each element of the Obsidian query syntax needed to be in a separate query string. Thanks for the clarification - with both path and tag in the single query string the query is working as expected. Thanks for the awesomely quick response!
