### ISSUE TITLE
Configurable font size

### ISSUE THREAD

**Issue by javiavid** [pashashocky/obsidian-note-gallery#3]
The size of the note content is very small compared to the size of the note title.
Is it possible to configure this?

<img width="571" alt="image" src="https://github.com/pashashocky/obsidian-note-gallery/assets/7627504/74f127d3-0718-44b4-8a04-0b0aa1d8bff1">

Thanks

**Comment by pashashocky** [comment]
For sure, this should be pretty straightforward.

**Comment by pashashocky** [comment]
Done, I changed the default to `6pt` from `4pt`. You can set it in the code block for now:
```
~~~note-gallery
fontsize: 10pt
~~~
```
