### ISSUE TITLE
Hardcoded limit of 10?

### ISSUE THREAD

**Issue by stakaz** [pashashocky/obsidian-note-gallery#47]
Hello, if a use a directory with more than 10 notes, only ten of them are shown regardless of the limit settings (numbers less than 10 work properly) . Is it correct behavior and if yes, could it be removed so the limit can be set by the user?

**Comment by pashashocky** [comment]
Take a look here:

**Comment by stakaz** [comment]
Oh man, I am sorry. I think, I fould the issue. It shows 10 elements if it is a preview in the editor view. In read view everything works.

**Comment by pashashocky** [comment]
Interesting, I'll take note, and do some testing when I have more time, I'm in `live preview` and it works in preview as well with:

```
~~~~note-gallery
query: 'path: atlas OR path: + OR path: calendar/notes'
debugQuery: false
spath: 
recursive: false
sort: desc
sortby: mtime
limit: 0
fontsize: 6pt
showTitle: true
~~~~

**Comment by stakaz** [comment]
OK, so I was wrong one more time. It worked and did not work spontaneously. With or without the limit option and I read and edit view. But after 'Drop all cache and...' option it started working anytime. So it could be a cache issue...
