### ISSUE TITLE
Feature request: hide the note titles

### ISSUE THREAD

**Issue by Nilahn** [pashashocky/obsidian-note-gallery#7]
Since many notes have their titles as a H1 Header, it uses up a lot of space when its shown twice in the gallery view (as the files title and as a h1 header). Would be great to have to option of not showing the file-titles.

**Comment by pashashocky** [comment]
This should be pretty quick to bang out, do you have anything against the `<hr />`? The line below the title, it's currently used to display whether the file is loaded from the cache or rendered live. 

I guess if I hide the title, i'd hide the `<hr />` as well...

**Comment by pashashocky** [comment]
This is now in release `0.0.32` - you can add another option `showTitle` to the code block @Nilahn

```
~~~note-gallery
showTitle: false
~~~
```

**Comment by Nilahn** [comment]
perfect!
