### ISSUE TITLE
[BUG] Gallery doesnt render in source mode by default

### ISSUE THREAD

**Issue by lucastucious** [pashashocky/obsidian-note-gallery#9]
in source mode, clicking switch to reading mode right now won't render gallery.
As we speaked [about on discord](https://discord.com/channels/686053708261228577/1160969028739793017/1179068121705885757)

https://github.com/pashashocky/obsidian-note-gallery/assets/28046122/191c95b2-b0fd-489e-94a9-74a3a2ef5b7e

**Comment by pashashocky** [comment]
More in-depth discussion in #23

**Comment by pashashocky** [comment]
Fixed in `0.0.59` thank you for your help debugging this! Was a pretty trivial fix tbh. Re-open if any issues!
